In [1]:
#Write a NumPy program to implement following operation
#to convert a list of numeric values into a one-dimensional NumPy array
#Grishma m. Jethva
#216270307051

import numpy as np 
a=[1,2,3,4,5] #create a list
print("Lis:",a)
b=np.array(a)
print("array:",b)

Lis: [1, 2, 3, 4, 5]
array: [1 2 3 4 5]


In [2]:
#to create a 3x3 matrix with values ranging from 2 to 10
#Grishma m. Jethva
#216270307051

import numpy as np
a= np.arange(2,11).reshape(3,3)

print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
